spring.application.name: worker
server.port: 9006

spring:
  cloud:
    openfeign:
      client:
        config:
          products-api:
            url: http://localhost:9001
          customer-api:
            url: http://localhost:9000
          bill-api:
            url: http://localhost:9004
          delivery-api:
            url: http://localhost:9005
    stream:
      bindings:
        #orderArrangements-in-0:
        proccessMessage-in-0:
          destination: OrderPaymentProcessing #exchange name
          group: orderingcreation1
          #consumer:
            #max-attempts: 20
      rabbit:
        bindings:
          proccessMessage-in-0:
            consumer:
              acknowledgeMode: manual
              requeueRejected: true
    rabbit:
      bindings:
        consumer:
          autoBindDlq: true


  rabbitmq:
    host: ${RMQ_HOSTNAME:localhost}
    port: ${RMQ_PORT:5672}
    username: ${RMQ_USERNAME:guest}
    password: ${RMQ_PASSWORD:guest}
