spring.application.name: order
server.port: 9003

spring:
#  datasource:
#    url: jdbc:postgresql://localhost/order
#    username: ${POSTGRES_USERNAME:postgres}
#    password: ${POSTGRES_PASSWORD:postgres}
#  jpa:
#    generate-ddl: true
#    show-sql: false


#  cloud:
#    stream:
#      bindings:



  rabbitmq:
    host: ${RMQ_HOSTNAME:localhost}
    port: ${RMQ_PORT:5672}
    username: ${RMQ_USERNAME:guest}
    password: ${RMQ_PASSWORD:guest}
