spring.application.name: order
server.port: 9003

spring:
#  datasource:
#    url: jdbc:postgresql://localhost/order
#    username: ${POSTGRES_USERNAME:postgres}
#    password: ${POSTGRES_PASSWORD:postgres}
#  jpa:
#    generate-ddl: true
#    show-sql: false



  cloud:
    openfeign:
      client:
        config:
          products-api:
            url: http://localhost:9001
          customer-api:
            url: http://localhost:9000
          bill-api:
            url: http://localhost:9004
          delivery-api:
            url: http://localhost:9005
    stream:
      bindings:
        orderProcess-in-0:
          destination: OrderProcessing1 #exchange name
          group: orderingcreation1
        orderProcess-out-0:
          #destination: OrderPopulation
          destination: OrderPaymentProcessing
          group: orderingcreation1



  rabbitmq:
    host: ${RMQ_HOSTNAME:localhost}
    port: ${RMQ_PORT:5672}
    username: ${RMQ_USERNAME:guest}
    password: ${RMQ_PASSWORD:guest}
